name: harry_potter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  http: ^1.2.0
  provider: ^6.1.2
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.12.0
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: HarryP
      fonts:
        - asset: assets/fonts/HARRYP__.ttf